plugins:
  - jekyll-remote-theme
#remote_theme: benbalter/retlab
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
locale: "en-US"
title: "Deep Time"
subtitle: "Early Career Network"
Description: "Increasing the visibility of the research undertaken by deep-time paleoscientists."
url: "https://deeptimeecn.github.io"
baseurl: "/Community"
repository: "DeepTimeECN/Community"
#head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - /assets/js/your-custom-head-script.js
#teaser:
logo: "assets/images/CrossSection_black.jpg"
masthead_title: "Deep Time Early Career Network"

