plugins:
  - jekyll-remote-theme
#remote_theme: benbalter/retlab
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
locale: "en-US"
title: "Deep Time"
subtitle: "Early Career Network"
Description: "Increasing the visibility of the research undertaken by deep-time paleoscientists."
url: "https://deeptimeecn.github.io"
baseurl: "/Community"
repository: "DeepTimeECN/Community"
logo: "/assets/images/logo.png"
masthead_title: "Deep Time Early Career Network"
search: true
twitter: "deeptimeecn"
